org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.newDsl=false
flutter.android-skip-build-dependency-validation=true
android-skip-build-dependency-validation=true
skip-build-dependency-validation=true
